### ISSUE TITLE
Error when opening or closing Anki

### ISSUE THREAD

**Issue by JynxLuckyJ** [ig3/anki-limitnew#7] opened 2021-05-26 00:43 UTC
Every time I open or close Anki I get the following error:

![anki_t3mNBhmIGQ](https://user-images.githubusercontent.com/46902581/119585436-4fff3e00-bd90-11eb-8480-158deeb57031.png)

The error also prevents Anki from closing, I have to kill it in the task manager.

I've tried disabling all my other add-ons and still have the same error.
I copied August version the add-on from another computer and it works fine. 

Any help would be greatly appreciated.

**Comment by ig3** [comment] 2021-05-26 22:46
Something is going wrong in parts of Anki that I know nothing about. I am surprised that you say an old version works but current doesn't. I developed the new version in response to a report that the old version didn't work on 2.1.35. But maybe the old version you have isn't as old as I am thinking. Could you zip the contents of your add-on directory with the version that is working and attach it here? Maybe I can find some clues in the difference between that and the current release.

Is it possible the old version doesn't cause on error on startup but also doesn't do anything useful? This is what I would expect with the old version on Anki 2.1.35 - one of the key hooks that it used was no longer called in 2.1.28 and later.

If you open a command window, find your Anki install directory (maybe C:\Program Files\Anki - or something like that) and run anki-console.exe, you might find some messages there that would help identify the root of the problem.

**Comment by JynxLuckyJ** [comment] 2021-05-27 04:15
The old version does limit my new cards, though I can't say whether it is is doing so as intended.

I did get a new error from running Anki from the command line:
![cmd_WEZXyDoegw](https://user-images.githubusercontent.com/46902581/119764572-47cdfe00-be77-11eb-9469-9cf94e2490d3.png)
![anki-console_MGEG2SexN1](https://user-images.githubusercontent.com/46902581/119764571-47356780-be77-11eb-97d3-a2a636978a18.png)


Here is the versionthat is working for me:
[548158563.zip](https://github.com/ig3/anki-limitnew/files/6551074/548158563.zip)

**Comment by ig3** [comment] 2021-05-27 06:32
Thanks for that. The old version is prior to the changes I made to accommodate 2.1.28 and later, and it appears that you are running 2.1.35. I must misunderstand something: I would have said that it is not possible for the old version to limit new cards in version 2.1.35. The hook function that is still called doesn't limit new cards - it just clears some cache items.

If you want to explore the old version, maybe you could add a print in the schedulerNewLimitForSingleDeck function. It would be a little interesting to know if that is executing.

But the latest version is probably a better place to focus attention. I loads successfully for me in Anki 2.1.44. 

With the latest plugin version, the tail of output in the console for me is:

```
C:\Program Files\Anki>anki-console.exe
[5480] PyInstaller Bootloader 3.x
[5480] LOADER: executable is C:\Program Files\Anki\anki-console.exe
[5480] LOADER: homepath is C:\Program Files\Anki
[5480] LOADER: _MEIPASS2 is NULL
[5480] LOADER: archivename is C:\Program Files\Anki\anki-console.exe
[5480] LOADER: C:\Program Files\Anki\anki-console.exe contains a digital signature
[5480] LOADER: No need to extract files to run; setting extractionpath to homepath
[5480] LOADER: SetDllDirectory(C:\Program Files\Anki)
[5480] LOADER: Already in the child - running user's code.
[5480] LOADER: Python library: C:\Program Files\Anki\python38.dll
[5480] LOADER: Loaded functions from Python library.
[5480] LOADER: Manipulating environment (sys.path, sys.prefix)
[5480] LOADER: sys.prefix is C:\Program Files\Anki
[5480] LOADER: Pre-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
[5480] LOADER: Setting runtime options
[5480] LOADER: Initializing python
[5480] LOADER: Overriding Python's sys.path
[5480] LOADER: Post-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
[5480] LOADER: Setting sys.argv
[5480] LOADER: setting sys._MEIPASS
[5480] LOADER: importing modules from CArchive
[5480] LOADER: extracted struct
[5480] LOADER: callfunction returned...
[5480] LOADER: extracted pyimod01_os_path
[5480] LOADER: callfunction returned...
[5480] LOADER: extracted pyimod02_archive
[5480] LOADER: callfunction returned...
[5480] LOADER: extracted pyimod03_importers
[5480] LOADER: callfunction returned...
[5480] LOADER: Installing PYZ archive with Python modules.
[5480] LOADER: PYZ archive: PYZ-00.pyz
[5480] LOADER: Running pyiboot01_bootstrap.py
[5480] LOADER: Running pyi_rth_win32comgenpy.py
[5480] LOADER: Running pyi_rth_multiprocessing.py
[5480] LOADER: Running pyi_rth_certifi.py
[5480] LOADER: Running pyi_rth_pyqt5.py
[5480] LOADER: Running pyi_rth_pkgres.py
[5480] LOADER: Running pyi_rth_pyqt5webengine.py
[5480] LOADER: Running runanki.py
total overdue  0
limitDeck  1621566559717
total overdue  0
deck overdue  1621566559717 0
maxNew  50 deck_id: 1621566559717
name: "Chinese Core 100"
level: 1
collapsed: true
new_count: 50

limitDeck  1
total overdue  0
deck overdue  1 0
maxNew  50 None
limitDeck  1621566852441
total overdue  0
deck overdue  1621566852441 0
maxNew  50 deck_id: 1621566852441
name: "ES2000"
level: 1
collapsed: true
new_count: 50

limitDeck  1621566221529
total overdue  0
deck overdue  1621566221529 0
maxNew  50 deck_id: 1621566221529
name: "Mandarin Chinese - From Beginner to Advanced (Demo)"
level: 1
collapsed: true
new_count: 50

limitDeck  1621567296645
total overdue  0
deck overdue  1621567296645 0
maxNew  50 deck_id: 1621567296645
name: "Mr Moffat\'s P5"
level: 1
collapsed: true
new_count: 50

limitDeck  1621571690458
total overdue  0
deck overdue  1621571690458 0
maxNew  50 deck_id: 1621571690458
name: "Physics - Particle Physics"
level: 1
collapsed: true
learn_count: 2
new_count: 50

limitDeck  1621567225402
total overdue  0
deck overdue  1621567225402 0
maxNew  50 deck_id: 1621567225402
name: "Pronunciaci\303\263n Mandar\303\255n niv. 1"
level: 1
collapsed: true
new_count: 35

limitDeck  1621566095327
total overdue  0
deck overdue  1621566095327 0
maxNew  50 deck_id: 1621566095327
name: "Systematic Approach to Chinese HSK 1"
level: 1
collapsed: true
new_count: 50

initialization complete
```

You aren't getting to initialization complete. 

It seems the expected deck configuration isn't loaded in your case.

Maybe you can add `print("conf ", conf)` in limitDeck in add_on_2_1_28.py, just after setting conf:

```
def limitDeck(deck_id):
    print("limitDeck ", deck_id)
    global totalCount
    global totalOverdue
    global lastDay
    enablePerDeckLimits = config.get('enablePerDeckLimits', True)
    enableTotalLimits = config.get('enableTotalLimits', True)
    conf = mw.col.decks.confForDid(deck_id)
    print("conf ", conf)
    newPerDay = conf['new']['perDay']
```

Then run anki-console.exe again and lets see what, if anything is coming back.

**Comment by ig3** [comment] 2021-05-27 20:17
I'm suspicious that Anki is calling the reviewer_did_answer_card hook before loading the collection, possibly when doing a sync during startup. I have updated the add-on to detect this and you may find that if you update it will load now. Please try the new version and let me know.

**Comment by JynxLuckyJ** [comment] 2021-05-28 00:11
Well I can't say why the old version would be working with my version. But it does limit the number of new cards I can review even if the Anki is still showing that there are more new cards to do. And as far as I can tell it is withing the limits I set. 

Unfortunately it still isn't working with the new update. 
To potentially aid in trouble shooting I have a fresh install of Anki 2.1.35 with only this add-on enabled.

I added the new line to "add_on_2_1_28.py".

> C:\Program Files\Anki>anki-console.exe
> [14696] PyInstaller Bootloader 3.x
> [14696] LOADER: executable is C:\Program Files\Anki\anki-console.exe
> [14696] LOADER: homepath is C:\Program Files\Anki
> [14696] LOADER: _MEIPASS2 is NULL
> [14696] LOADER: archivename is C:\Program Files\Anki\anki-console.exe
> [14696] LOADER: C:\Program Files\Anki\anki-console.exe contains a digital signature
> [14696] LOADER: No need to extract files to run; setting extractionpath to homepath
> [14696] LOADER: SetDllDirectory(C:\Program Files\Anki)
> [14696] LOADER: Already in the child - running user's code.
> [14696] LOADER: Python library: C:\Program Files\Anki\python38.dll
> [14696] LOADER: Loaded functions from Python library.
> [14696] LOADER: Manipulating environment (sys.path, sys.prefix)
> [14696] LOADER: sys.prefix is C:\Program Files\Anki
> [14696] LOADER: Pre-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
> [14696] LOADER: Setting runtime options
> [14696] LOADER: Initializing python
> [14696] LOADER: Overriding Python's sys.path
> [14696] LOADER: Post-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
> [14696] LOADER: Setting sys.argv
> [14696] LOADER: setting sys._MEIPASS
> [14696] LOADER: importing modules from CArchive
> [14696] LOADER: extracted struct
> [14696] LOADER: callfunction returned...
> [14696] LOADER: extracted pyimod01_os_path
> [14696] LOADER: callfunction returned...
> [14696] LOADER: extracted pyimod02_archive
> [14696] LOADER: callfunction returned...
> [14696] LOADER: extracted pyimod03_importers
> [14696] LOADER: callfunction returned...
> [14696] LOADER: Installing PYZ archive with Python modules.
> [14696] LOADER: PYZ archive: PYZ-00.pyz
> [14696] LOADER: Running pyiboot01_bootstrap.py
> [14696] LOADER: Running pyi_rth_win32comgenpy.py
> [14696] LOADER: Running pyi_rth_multiprocessing.py
> [14696] LOADER: Running pyi_rth_certifi.py
> [14696] LOADER: Running pyi_rth_pyqt5.py
> [14696] LOADER: Running pyi_rth_pkgres.py
> [14696] LOADER: Running pyi_rth_pyqt5webengine.py
> [14696] LOADER: Running runanki.py
> mpv too old for key rebinding
> limitDeck  1
> conf  {'id': 1, 'mod': 0, 'name': 'Default', 'usn': 0, 'maxTaken': 60, 'autoplay': True, 'timer': 0, 'replayq': True, 'new': {'bury': False, 'delays': [1.0, 10.0], 'initialFactor': 2500, 'ints': [1, 4, 0], 'order': 1, 'perDay': 20}, 'rev': {'bury': False, 'ease4': 1.3, 'ivlFct': 1.0, 'maxIvl': 36500, 'perDay': 200, 'hardFactor': 1.2}, 'lapse': {'delays': [10.0], 'leechAction': 1, 'leechFails': 8, 'minInt': 1, 'mult': 0.0}, 'dyn': False}
> deck overdue  1 0
> maxNew  20 None
> limitDeck  1620671635617
> Traceback (most recent call last):
>   File "aqt\main.py", line 520, in loadCollection
>   File "aqt\gui_hooks.py", line 819, in __call__
>   File "C:\Users\Joe\AppData\Roaming\Anki2\addons21\548158563\versions\add_on_2_1_28.py", line 309, in onCollectionDidLoad
>     limitDeck(x.id)
>   File "C:\Users\Joe\AppData\Roaming\Anki2\addons21\548158563\versions\add_on_2_1_28.py", line 183, in limitDeck
>     newPerDay = conf['new']['perDay']
> KeyError: 'new'
> Caught exception:
> Traceback (most recent call last):
>   File "aqt\taskman.py", line 87, in _on_closures_pending
>   File "aqt\taskman.py", line 59, in <lambda>
>   File "aqt\taskman.py", line 76, in wrapped_done
>   File "aqt\sync.py", line 114, in on_future_done
>   File "aqt\main.py", line 912, in on_collection_sync_finished
>   File "aqt\main.py", line 699, in reset
>   File "aqt\main.py", line 661, in moveToState
> AttributeError: 'AnkiQt' object has no attribute '_startupState'

And I get 2 Error windows when Anki starts:
![anki-console_LMzgMHom2o](https://user-images.githubusercontent.com/46902581/119911229-7fdc4c00-bf1e-11eb-92a6-d887ad65f2fa.png)
![anki-console_ndii0M6c7A](https://user-images.githubusercontent.com/46902581/119911231-8074e280-bf1e-11eb-87b1-9b4fbda4da8b.png)

**Comment by ig3** [comment] 2021-05-28 00:32
Unfortunately, I can't reproduce the fault, so I will have to trouble you to keep testing.

I have uploaded another update. Maybe this one will get through the initialization. Please try again and let me know.

Looking for clues I found [this bug report](https://github.com/ankidroid/Anki-Android/issues/6880). In it, they deal with a deck with missing configuration. One of the suggestions there is to check the database. Please try that, if you haven't already. It seems, at least in the past, deck configurations could go missing.

**Comment by JynxLuckyJ** [comment] 2021-05-28 03:14
This new update seems like it might have done the job, At least I don't get an error when Anki launches or closes. 

I'll let you know if it is limiting my new cards properly when I do my reps tomorrow.

Thank you very much for all the effort you've put in for me and your quick replies.

**Comment by ig3** [comment] 2021-05-28 04:27
I hope it works well enough. You have at least one deck that it is not handling. With the latest change, it will mostly ignore it (any deck for which it doesn't get configuration). But it would be good to better understand what is going on. If you run the new version from the console and paste the output here, that might help. Thanks for your patience.

**Comment by JynxLuckyJ** [comment] 2021-05-29 00:34
Sure thing, This is what I got now:

> C:\Program Files\Anki>anki-console.exe
> [7364] PyInstaller Bootloader 3.x
> [7364] LOADER: executable is C:\Program Files\Anki\anki-console.exe
> [7364] LOADER: homepath is C:\Program Files\Anki
> [7364] LOADER: _MEIPASS2 is NULL
> [7364] LOADER: archivename is C:\Program Files\Anki\anki-console.exe
> [7364] LOADER: C:\Program Files\Anki\anki-console.exe contains a digital signature
> [7364] LOADER: No need to extract files to run; setting extractionpath to homepath
> [7364] LOADER: SetDllDirectory(C:\Program Files\Anki)
> [7364] LOADER: Already in the child - running user's code.
> [7364] LOADER: Python library: C:\Program Files\Anki\python38.dll
> [7364] LOADER: Loaded functions from Python library.
> [7364] LOADER: Manipulating environment (sys.path, sys.prefix)
> [7364] LOADER: sys.prefix is C:\Program Files\Anki
> [7364] LOADER: Pre-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
> [7364] LOADER: Setting runtime options
> [7364] LOADER: Initializing python
> [7364] LOADER: Overriding Python's sys.path
> [7364] LOADER: Post-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
> [7364] LOADER: Setting sys.argv
> [7364] LOADER: setting sys._MEIPASS
> [7364] LOADER: importing modules from CArchive
> [7364] LOADER: extracted struct
> [7364] LOADER: callfunction returned...
> [7364] LOADER: extracted pyimod01_os_path
> [7364] LOADER: callfunction returned...
> [7364] LOADER: extracted pyimod02_archive
> [7364] LOADER: callfunction returned...
> [7364] LOADER: extracted pyimod03_importers
> [7364] LOADER: callfunction returned...
> [7364] LOADER: Installing PYZ archive with Python modules.
> [7364] LOADER: PYZ archive: PYZ-00.pyz
> [7364] LOADER: Running pyiboot01_bootstrap.py
> [7364] LOADER: Running pyi_rth_win32comgenpy.py
> [7364] LOADER: Running pyi_rth_multiprocessing.py
> [7364] LOADER: Running pyi_rth_certifi.py
> [7364] LOADER: Running pyi_rth_pyqt5.py
> [7364] LOADER: Running pyi_rth_pkgres.py
> [7364] LOADER: Running pyi_rth_pyqt5webengine.py
> [7364] LOADER: Running runanki.py
> mpv too old for key rebinding
> ADDED THROUGH JP
> onCollectionDidLoad
> limitDeck  1
> deck overdue  1 0
> maxNew  20 None
> limitDeck  1620671635617
> conf has no configuration for new!!
> conf  {'id': 1620671635617, 'mod': 1622227211, 'name': 'Filtered Deck 1', 'usn': 140, 'lrnToday': [19, 0], 'revToday': [19, 7], 'newToday': [19, 0], 'timeToday': [19, 619584], 'collapsed': False, 'browserCollapsed': False, 'desc': '', 'dyn': 1, 'resched': True, 'terms': [['"deck:日本語" is:due', 28, 2]], 'separate': True, 'delays': None, 'previewDelay': 10}
> limitDeck  1620588704062
> deck overdue  1620588704062 8
> maxNew  1 deck_id: 1620588704062
> name: "Graded Readers"
> level: 1
> review_count: 8
> new_count: 1
> 
> limitDeck  1620588702587
> deck overdue  1620588702587 0
> maxNew  20 deck_id: 1620588702587
> name: "Retired Cards"
> level: 1
> 
> limitDeck  1620588702577
> deck overdue  1620588702577 0
> maxNew  5 deck_id: 1620588702577
> name: "\346\227\245\346\234\254\350\252\236"
> children {
>   deck_id: 1620588704066
>   name: "0 - Japanese Grammar"
>   children {
>     deck_id: 1620588704068
>     name: "0. Introduction"
>     level: 3
>   }
>   children {
>     deck_id: 1620588704560
>     name: "1. Lessons"
>     level: 3
>   }
>   level: 2
> }
> children {
>   deck_id: 1620588702579
>   name: "1 - Japanese Minimal Pairs"
>   level: 2
> }
> children {
>   deck_id: 1620588704072
>   name: "2 - \345\255\227(\343\201\230)"
>   children {
>     deck_id: 1620588704075
>     name: "Kanji"
>     children {
>       deck_id: 1620588704076
>       name: "Recognize"
>       level: 4
>     }
>     children {
>       deck_id: 1620588704079
>       name: "Write"
>       level: 4
>     }
>     level: 3
>   }
>   level: 2
> }
> children {
>   deck_id: 1620588702593
>   name: "4 - Sentences"
>   level: 2
>   learn_count: 1
>   new_count: 1
> }
> children {
>   deck_id: 1620588702588
>   name: "5 - Listening"
>   children {
>     deck_id: 1620588704587
>     name: "1. Vocabulary Core Anime"
>     children {
>       deck_id: 1620588704589
>       name: "1.The Basics"
>       children {
>         deck_id: 1620588704608
>         name: "1.Politeness"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704596
>         name: "2.Particles and Copula"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704600
>         name: "3.Pronouns and Interjections"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704611
>         name: "4.Verbs and I-Adjectives"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704605
>         name: "5.Conjugations"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704623
>         name: "6.Grammar"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704602
>         name: "7.Nouns"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704619
>         name: "8.Kosoado"
>         level: 5
>       }
>       children {
>         deck_id: 1620588704591
>         name: "9.Adverbs"
>         level: 5
>       }
>       level: 4
>     }
>     children {
>       deck_id: 1620588704593
>       name: "2.Vocabulary"
>       level: 4
>       new_count: 1
>     }
>     level: 3
>     new_count: 1
>   }
>   children {
>     deck_id: 1620588702590
>     name: "Jalup Beginner"
>     level: 3
>     new_count: 1
>   }
>   children {
>     deck_id: 1620588702921
>     name: "Nayr 5K Sentences"
>     level: 3
>     new_count: 1
>   }
>   level: 2
>   new_count: 1
> }
> level: 1
> learn_count: 1
> new_count: 1
> 
> limitDeck  1620588704066
> deck overdue  1620588704066 0
> maxNew  40 deck_id: 1620588704066
> name: "0 - Japanese Grammar"
> children {
>   deck_id: 1620588704068
>   name: "0. Introduction"
>   level: 3
> }
> children {
>   deck_id: 1620588704560
>   name: "1. Lessons"
>   level: 3
> }
> level: 2
> 
> limitDeck  1620588704068
> deck overdue  1620588704068 0
> maxNew  1 deck_id: 1620588704068
> name: "0. Introduction"
> level: 3
> 
> limitDeck  1620588704560
> deck overdue  1620588704560 0
> maxNew  1 deck_id: 1620588704560
> name: "1. Lessons"
> level: 3
> 
> limitDeck  1620588702579
> deck overdue  1620588702579 0
> maxNew  20 deck_id: 1620588702579
> name: "1 - Japanese Minimal Pairs"
> level: 2
> 
> limitDeck  1620588704072
> deck overdue  1620588704072 0
> maxNew  40 deck_id: 1620588704072
> name: "2 - \345\255\227(\343\201\230)"
> children {
>   deck_id: 1620588704075
>   name: "Kanji"
>   children {
>     deck_id: 1620588704076
>     name: "Recognize"
>     level: 4
>   }
>   children {
>     deck_id: 1620588704079
>     name: "Write"
>     level: 4
>   }
>   level: 3
> }
> level: 2
> 
> limitDeck  1620588704075
> deck overdue  1620588704075 0
> maxNew  40 deck_id: 1620588704075
> name: "Kanji"
> children {
>   deck_id: 1620588704076
>   name: "Recognize"
>   level: 4
> }
> children {
>   deck_id: 1620588704079
>   name: "Write"
>   level: 4
> }
> level: 3
> 
> limitDeck  1620588704076
> deck overdue  1620588704076 0
> maxNew  1 deck_id: 1620588704076
> name: "Recognize"
> level: 4
> 
> limitDeck  1620588704079
> deck overdue  1620588704079 0
> maxNew  1 deck_id: 1620588704079
> name: "Write"
> level: 4
> 
> limitDeck  1620588702593
> deck overdue  1620588702593 0
> maxNew  1 deck_id: 1620588702593
> name: "4 - Sentences"
> level: 2
> learn_count: 1
> new_count: 1
> 
> limitDeck  1620588702588
> deck overdue  1620588702588 0
> maxNew  12 deck_id: 1620588702588
> name: "5 - Listening"
> children {
>   deck_id: 1620588704587
>   name: "1. Vocabulary Core Anime"
>   children {
>     deck_id: 1620588704589
>     name: "1.The Basics"
>     children {
>       deck_id: 1620588704608
>       name: "1.Politeness"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704596
>       name: "2.Particles and Copula"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704600
>       name: "3.Pronouns and Interjections"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704611
>       name: "4.Verbs and I-Adjectives"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704605
>       name: "5.Conjugations"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704623
>       name: "6.Grammar"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704602
>       name: "7.Nouns"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704619
>       name: "8.Kosoado"
>       level: 5
>     }
>     children {
>       deck_id: 1620588704591
>       name: "9.Adverbs"
>       level: 5
>     }
>     level: 4
>   }
>   children {
>     deck_id: 1620588704593
>     name: "2.Vocabulary"
>     level: 4
>     new_count: 1
>   }
>   level: 3
>   new_count: 1
> }
> children {
>   deck_id: 1620588702590
>   name: "Jalup Beginner"
>   level: 3
>   new_count: 1
> }
> children {
>   deck_id: 1620588702921
>   name: "Nayr 5K Sentences"
>   level: 3
>   new_count: 1
> }
> level: 2
> new_count: 1
> 
> limitDeck  1620588704587
> deck overdue  1620588704587 0
> maxNew  12 deck_id: 1620588704587
> name: "1. Vocabulary Core Anime"
> children {
>   deck_id: 1620588704589
>   name: "1.The Basics"
>   children {
>     deck_id: 1620588704608
>     name: "1.Politeness"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704596
>     name: "2.Particles and Copula"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704600
>     name: "3.Pronouns and Interjections"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704611
>     name: "4.Verbs and I-Adjectives"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704605
>     name: "5.Conjugations"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704623
>     name: "6.Grammar"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704602
>     name: "7.Nouns"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704619
>     name: "8.Kosoado"
>     level: 5
>   }
>   children {
>     deck_id: 1620588704591
>     name: "9.Adverbs"
>     level: 5
>   }
>   level: 4
> }
> children {
>   deck_id: 1620588704593
>   name: "2.Vocabulary"
>   level: 4
>   new_count: 1
> }
> level: 3
> new_count: 1
> 
> limitDeck  1620588704589
> deck overdue  1620588704589 0
> maxNew  12 deck_id: 1620588704589
> name: "1.The Basics"
> children {
>   deck_id: 1620588704608
>   name: "1.Politeness"
>   level: 5
> }
> children {
>   deck_id: 1620588704596
>   name: "2.Particles and Copula"
>   level: 5
> }
> children {
>   deck_id: 1620588704600
>   name: "3.Pronouns and Interjections"
>   level: 5
> }
> children {
>   deck_id: 1620588704611
>   name: "4.Verbs and I-Adjectives"
>   level: 5
> }
> children {
>   deck_id: 1620588704605
>   name: "5.Conjugations"
>   level: 5
> }
> children {
>   deck_id: 1620588704623
>   name: "6.Grammar"
>   level: 5
> }
> children {
>   deck_id: 1620588704602
>   name: "7.Nouns"
>   level: 5
> }
> children {
>   deck_id: 1620588704619
>   name: "8.Kosoado"
>   level: 5
> }
> children {
>   deck_id: 1620588704591
>   name: "9.Adverbs"
>   level: 5
> }
> level: 4
> 
> limitDeck  1620588704608
> deck overdue  1620588704608 0
> maxNew  12 deck_id: 1620588704608
> name: "1.Politeness"
> level: 5
> 
> limitDeck  1620588704596
> deck overdue  1620588704596 0
> maxNew  12 deck_id: 1620588704596
> name: "2.Particles and Copula"
> level: 5
> 
> limitDeck  1620588704600
> deck overdue  1620588704600 0
> maxNew  12 deck_id: 1620588704600
> name: "3.Pronouns and Interjections"
> level: 5
> 
> limitDeck  1620588704611
> deck overdue  1620588704611 0
> maxNew  12 deck_id: 1620588704611
> name: "4.Verbs and I-Adjectives"
> level: 5
> 
> limitDeck  1620588704605
> deck overdue  1620588704605 0
> maxNew  12 deck_id: 1620588704605
> name: "5.Conjugations"
> level: 5
> 
> limitDeck  1620588704623
> deck overdue  1620588704623 0
> maxNew  12 deck_id: 1620588704623
> name: "6.Grammar"
> level: 5
> 
> limitDeck  1620588704602
> deck overdue  1620588704602 0
> maxNew  12 deck_id: 1620588704602
> name: "7.Nouns"
> level: 5
> 
> limitDeck  1620588704619
> deck overdue  1620588704619 0
> maxNew  12 deck_id: 1620588704619
> name: "8.Kosoado"
> level: 5
> 
> limitDeck  1620588704591
> deck overdue  1620588704591 0
> maxNew  12 deck_id: 1620588704591
> name: "9.Adverbs"
> level: 5
> 
> limitDeck  1620588704593
> deck overdue  1620588704593 0
> maxNew  12 deck_id: 1620588704593
> name: "2.Vocabulary"
> level: 4
> new_count: 1
> 
> limitDeck  1620588702590
> deck overdue  1620588702590 0
> maxNew  12 deck_id: 1620588702590
> name: "Jalup Beginner"
> level: 3
> new_count: 1
> 
> limitDeck  1620588702921
> deck overdue  1620588702921 0
> maxNew  12 deck_id: 1620588702921
> name: "Nayr 5K Sentences"
> level: 3
> new_count: 1
> 
> initialization complete
> FFMPEG already installed or conversion disabled.
> decks.allIds() is deprecated, use .all_names_and_ids()

As far as I can tell everything seems to be working but let me know if you see anything wrong.

**Comment by ig3** [comment] 2021-05-29 06:22
That looks much better. The only deck that was an issue is Filtered Deck 1 which doesn't have the usual deck configuration. I don't use filtered decks so haven't noticed. It will mostly be ignored now. New cards will not be limited in it, but that's probably appropriate. I think you should be OK now but do let me know if you have any further issues.

Thank you very much for letting me know about your issue and your patience to investigate it.

**Comment by ig3** [comment] 2021-06-05 02:09
I'll close this now, on the bases of recent changes having fixed the fault but feel free to reopen or open a new issue if you have any further problems.

**Closed as completed by ig3** 2021-06-05 02:09 UTC
